#!name=彩云天气pro

#!desc=彩云天气pro

[Script]

#彩云天气pro=type=http-response,pattern=^http[s]?:\/\/biz\.(caiyunapp|cyapi)\.(com|cn)\/v2\/user.*$,requires-body=1,script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/caiyuntianqi.js
# hostname = *.cyapi.cn, *.caiyunapp.com, adx.sogaha.cn
彩云天气-SVIP会员 = type=http-response,pattern=^https?:\/\/(biz|wrapper|starplucker)\.(cyapi|caiyunapp)\.(cn|com)\/(.+\/(user\?app_name|activity\?app_name|visitors|operation\/banners)|p\/v\d\/(vip_info|user_info)),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/caiyuntianqi.js
彩云天气-SVIP地图 = type=http-request,pattern=^https?:\/\/(api|wrapper)\.(cyapi|caiyunapp)\.(cn|com)\/v\d\/(satellite|nafp\/origin_images),requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/caiyuntianqi.js
[MITM]

hostname= %APPEND% *.caiyunapp.com, *.cyapi.com, *.cyapi.cn, *.caiyunapp.cn, adx.sogaha.cn

[URL Rewrite]

^https:\/\/ad\.caiyunapp\.com\/ _ reject
