#!/bin/bash

#======================================================
#   System Required:  Debian 10+ 
#   Description: Manage clash
#   Author: J. 2021.12.20
#======================================================

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
plain='\033[0m'

url_cdn="https://gh.api.99988866.xyz"
echo "199.232.68.133 raw.githubusercontent.com" >> /etc/hosts

#wget -O /usr/bin/clash_ui ${webget}/https://raw.githubusercontent.com/fjjonline/c-m/main/clash_ui >> /dev/null 2>&1
wget -O /usr/bin/clash_ui https://cdn.jsdelivr.net/gh/fjjonline/c-m@main/clash_ui >> /dev/null 2>&1
chmod +x /usr/bin/clash_ui >> /dev/null 2>&1
echo "---------------------------------------"
echo -e "${green}Clash_ui 安装成功${plain}"
echo -e "${green}Clash_UI使用方法 clash_ui${plain}"
echo -e "${green}第一次请用命令安装 clash_ui install${plain}"
echo "---------------------------------------"
clash_ui install
