log:
  level: info   
  file: /tmp/mosdns.log
 
plugin:
  - tag: main_server
    type: server
    args:
      entry:
        - _single_flight
        - _no_ecs
        - lazy_cache
        - main_sequence
      server:                       
        - protocol: udp             
          addr: 0.0.0.0:53          
        - protocol: tcp
          addr: 0.0.0.0:53

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain
          exec:
            - _block_with_nxdomain
            - _return
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - _return
        - if:
            - query_is_non_local_domain
          exec:
            - if:
                - _qtype_AAAA
              exec:
                - _block_with_empty_response
                - _return
            - forward_remote
            - _return
        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - if:
                - _qtype_AAAA
              exec:
                - _block_with_empty_response
                - _return
            - forward_remote
          fast_fallback: 150
          always_standby: true

  - tag: forward_local
    type: fast_forward
    args:
      upstream:     
        - addr: 119.29.29.29
          trusted: true
          idle_timeout: 30
        - addr: 223.6.6.6
          trusted: true
          idle_timeout: 30
        - addr: 114.114.114.114
          trusted: true
          idle_timeout: 30

  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
          addr: 127.0.0.1:5352
          trusted: true

  - tag: lazy_cache
    type: cache
    args:
      size: 4096
      lazy_cache_ttl: 259200

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:category-ads-all'

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'


